services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduled-order-middleman
    restart: on-failure:3
    # image: jogdensft/scheduledordermiddleman-scheduler:latest
    ports:
      - "3000:3000"
    user: "10001:${GID}"
    # Persist logs and queue backups
    volumes:
      - type: bind
        source: /data/scheduler_files/secrets
        target: /app/secrets
        is_directory: true
      - type: bind
        source: /data/scheduler_files/logs
        target: /app/src/logs
        is_directory: true
      - type: bind
        source: /data/scheduler_files/queue_backups
        target: /app/src/queue_backups
        is_directory: true

    # Environment variables (customize as needed)
    environment:
      # - TZ=America/New_York
      # Override secret file paths to use Docker secrets location
      - GOOGLE_API_KEY_FILE=/app/secrets/db-key.json
      - RYO_FTP_CREDS_FILE=/app/secrets/ryo_ftp_creds.json
      - SAS_FTP_CREDS_FILE=/app/secrets/sas_ftp_creds.json
      - SFT_WEBSITE_CREDS_FILE=/app/secrets/sft_creds.json
      # Database configuration (from production.env - optional overrides)
      # Uncomment and modify these to override production.env values
      - DATABASE_ID=15D6mO0PSfwKd5MeeycV2tP7FATOF0OfpJDNgygQ9NL0
      - DATABASE_BASE_SCHEDULE_ID=184714754
      - DATABASE_ORDER_LOG_ID=850759335
      - DATABASE_REFRESH_INTERVAL=3600
      - DATABASE_WRITE_INTERVAL=30
      # File Serve Configuration
      - FILE_SERVE_HOST=0.0.0.0
      - FILE_SERVE_PORT=3000
      # Alerts Emails
      - ALERTS_EMAIL=info@sweetfiretobacco.com
      - ALERTS_EMAIL_PWD=${ALERTS_EMAIL_PWD:?}
      - ALERTS_RECIPIENTS=["jacob.ogden@sweetfiretobacco.com"]
      # TZ
      - TZ=America/New_York

    # Healthcheck (optional - adjust based on your needs)
    healthcheck:
      # bash -c "[[ $(date -d "$(cat /app/src/logs/heartbeat.txt)" +"%s") -gt $(($(date +"%s") - 180)) ]] && exit 0 || exit 1"
      test:
        [
          "CMD",
          "bash",
          "-c",
          "[[ $(date -d '$(cat /app/src/logs/heartbeat.txt)' +'%s') -gt $(($(date +'%s') - 180)) ]] && exit 0 || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s

    labels:
      - traefik.enable=true
      - "traefik.http.routers.<unique_router_name>.rule=Host(`shadowarcanist.com`) && PathPrefix(`/`)"
      - traefik.http.routers.<unique_router_name>.entryPoints=http
