[project]
  dependencies = [
    "aiohttp==3.*",
    "aiologic==0.16.*",
    "aiorwlock==1.*",
    "apscheduler==3.*",
    "gspread==6.*",
    "pandas[performance]==3.*",
    "paramiko==5.*",
    "pydantic-settings==2.*",
    "pydantic==2.*",
    "python-dateutil==2.9.*",
    "rich==15.*",
    "sft-ext==0.7.1",
    "tzdata>=2025.3",
    "uvloop>=0.22.1 ; sys_platform == 'linux'",
    "winloop>=0.6.0 ; sys_platform == 'win32'",
  ]
  name = "scheduledinvoiceprocessor"
  requires-python = ">=3.14"
  version = "1.1.0"


[tool.uv]
  environments = [
    "sys_platform == 'linux'",
    "sys_platform == 'win32'",
  ]

  [tool.uv.sources]
    sft-ext = [
      { git = "https://github.com/AetherBreaker/sft_ext", marker = "sys_platform == 'linux'", tag = "v0.7.1" },
      { path = "D:\\SFT Software Projects\\sft_ext", editable = true, marker = "sys_platform == 'win32'" },
    ]

[tool.ruff]
  extend = "../pyproject.toml"

  src = [
    "./src",
  ]

[dependency-groups]
  dev = [
    "apscheduler-stubs>=0.1.0.dev2",
    "mypy>=2.1.0",
    "pandas-stubs>=3.0.0.260204",
    "types-python-dateutil>=2.9.0.20260323",
  ]

[tool.pyright]
  extraPaths = [
    "src",
  ]
  typeCheckingMode = "standard"

  executionEnvironments = [
    { root = "src", extraPaths = [
      "src",
    ] },
  ]
